version: 2
jobs:
  test-export:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
    environment:
      - NODE_ENV: development
    steps:
        - checkout
        - run: sudo npm install -g npm
        - run: sudo npm install -g gulp-cli
        - run: npm ci
        - run: gulp build
        - run: gulp update-css
  test-site:
     docker:
       - image: circleci/ruby:2.5.1-node-browsers
         environment:
           BUNDLER_VERSION: 2.0.2
     steps:
       - checkout
       - run:
           name: setup bundler
           command: |
             sudo gem update --system
             sudo gem install bundler
       - run: cd website/ && bundle install
       - run: cd website/ && bundle exec jekyll build

  build-production-export:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3
    environment:
      - NODE_ENV: development
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: sudo npm install -g gulp-cli
      - run: npm ci
      - run: gulp build
      - run: gulp update-css
      - deploy:
          name: Deploy Production
          command: bash .circleci/deploy-sporticon-design.sh
  deploy-site:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.2
    steps:
      - checkout
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem install bundler
      - run: cd website/ && bundle install
      - run: cd website/ && bundle exec jekyll build
      - deploy:
          name: Deploy Site to GitHub
          command: bash .circleci/deploy-website.sh
workflows:
  version: 2
  build:
    jobs:
      - test-export
      - test-site
      - build-production-export:
          requires:
            - test-export
          filters:
            branches:
              only: master
      - deploy-site:
          requires:
            - test-site
            - build-production-export
          filters:
            branches:
              only: master
