version: 2
jobs:
  build-production:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.0
    environment:
      - NODE_ENV: development
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: sudo npm install -g gulp-cli
      - run: npm install
      - run: gulp build
      - run: gulp update-css
      - deploy:
          name: Deploy Production
          command: bash .circleci/deploy-production.sh
  deploy-site:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.2
    steps:
      - checkout
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem install bundler
      - run: cd docs/ && bundle install
      - run: cd docs/ && bundle exec jekyll build
      - deploy:
          name: Deploy Site to GitHub
          command: bash .circleci/deploy-gh-pages.sh
workflows:
  version: 2
  build:
    jobs:
      - build-production: 
          filters:
            branches:
              only: develop
      - deploy-site:
          filters:
            branches:
              only: master
          