title: Player! Sporticon
email: design@ookamiinc.com
description: >- # this means to ignore newlines until "baseurl:"
  Player! Sporticon is a simple, delightfully crafted set of symbols 
  made to represent sports from a wide range of disciplines. 
  Our symbols are free for everyone to use; in your digital products, 
  prints and marketing assets. 
baseurl: "" 
url: "sporticon.ookami.tokyo"
twitter_username: player_twi
github_username:  ookami

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-polyglot

# Server Config options
livereload: true 

# Localization
# Localize
defaults:
    -
     scope:
         path: ""
     values:
         lang: en
         base-url: "/"
    -
     scope:
         path: ja
     values:
         lang: ja
         base-url: "/ja/"

# languages: ["en", "ja"]
# default_lang: "en"
# exclude_from_localization: ["javascript", "images", "css"]
# parallel_localization: true