baseurl: "" 
url: "sporticon.ookami.tokyo"

# Build settings
markdown: kramdown

# Server Config options
livereload: true 

# Localization
# Localize
defaults:
    -
     scope:
         path: ""
     values:
         lang: en
         base-url: "/"
    -
     scope:
         path: ja
     values:
         lang: ja
         base-url: "/ja/"

